// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxoNYDn9yUmoRLT6SaPYHkoIX3Xa5uDnc',
    appId: '1:345651230570:web:ebdcfb1ddce14dfe305713',
    messagingSenderId: '345651230570',
    projectId: 'flutter-notification-64fab',
    authDomain: 'flutter-notification-64fab.firebaseapp.com',
    storageBucket: 'flutter-notification-64fab.appspot.com',
    measurementId: 'G-1H1DWKRXXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxhwZQlBU-3P-8d4mJN3xEAnFbhCiVaQE',
    appId: '1:345651230570:android:e0c6880468599b38305713',
    messagingSenderId: '345651230570',
    projectId: 'flutter-notification-64fab',
    storageBucket: 'flutter-notification-64fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCREVrrjeGMsdaDt6hzQoOBOECZN0QDPes',
    appId: '1:345651230570:ios:49daf4ff7eb5b47d305713',
    messagingSenderId: '345651230570',
    projectId: 'flutter-notification-64fab',
    storageBucket: 'flutter-notification-64fab.appspot.com',
    iosBundleId: 'com.example.notification',
  );
}
